# For further information on the warnings visit
# https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md

default: true

# Material for MkDocs needs 4 spaces to work
MD007:
  indent: 4

# Disable line length warnings
MD013: false

# Allow some exceptions for inline HTML
MD033:
  allowed_elements: ['nobr', 'picture', 'source', 'img', 'figure', 'figcaption']

# Disables code block style checks because of syntax for "!!! Note"
MD046: false
