# Config file for cargo about
# For all options see https://embarkstudios.github.io/cargo-about/cli/generate/config.html

# If you add a license in the following section also consider changing deny.toml
accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause"
]

targets = [
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl"
]

ignore-dev-dependencies = true

[unicode-ident]
accepted = ["Unicode-DFS-2016"]


