version = 'v1'

# Mutating hooks are currently a beta feature. The configuration interface
# and the communication protocol between the server and hooks are unstable
# and can change at any time.
[[mutating_hooks]]
name = 'example_hook'
prio = 10
