apiVersion: v0.1
workloads:
  simple_test_with_a_long_name.test:
    runtime: podman
    agent: agent_A
    restartPolicy: ON_FAILURE
    tags:
      - key: owner
        value: Ankaios team
    runtimeConfig: |
      image: docker.io/nginx:latest
      commandOptions: ["-p", "8081:80"]
