#!/bin/bash

# Copyright (c) 2024 Elektrobit Automotive GmbH
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

# filename is intentionally without extension
# the script is called to invoke the plantuml cli command

if [ -n "${JAVA_HOME}" ] && [ -x "${JAVA_HOME}/bin/java" ] ; then
    JAVA="${JAVA_HOME}/bin/java"
elif [ -x /usr/bin/java ] ; then
    JAVA=/usr/bin/java
    JAVA_HOME=$(dirname $(realpath "${JAVA}"))/..
else
    echo Cannot find JVM >&2
    exit 1
fi

HEADLESS=
if [ -z "$DISPLAY" ] || ! [ -e "${JAVA_HOME}/lib/libawt_xawt.so" ] ; then
    HEADLESS=-Djava.awt.headless=true
fi

exec "$JAVA" -Djava.net.useSystemProxies=true $HEADLESS -jar /usr/local/bin/plantuml.jar "$@"
