@startuml seq_workload_update
!include ../../../../resources/doc/plantuml/clean.skin

participant "<<RuntimeAdapter>>" as runtime_adapter
participant "Workload Facade" as wl_facade
participant "Workload Facade Task" as wl_facade_task
participant "specific Workload\n e.g. PodmanWorkload" as specific_wl
participant "new specific Workload\n e.g. PodmanWorkload" as specific_wl_new


activate runtime_adapter


runtime_adapter -> wl_facade ++: update (new specific Workload) 

wl_facade ->> wl_facade_task : send an "Update" command \n and the new Workload object \n over the communication channel
note right
    For more details about the
    channel see the start sequence
end note
activate wl_facade_task

wl_facade -->> runtime_adapter --:

wl_facade_task -> specific_wl ++: stop specific Workload

specific_wl -> specific_wl ++--: do runtime specific \n stop Workload actions
note over specific_wl
The stop Workload actions
could be stopping and 
deleting a container as 
in the case of Podman
end note

specific_wl -->> wl_facade_task --

destroy specific_wl

wl_facade_task -> specific_wl_new ++: start specific Workload

specific_wl_new -> specific_wl_new ++--: do runtime specific \n start Workload actions
note over specific_wl_new
    The start Workload actions
    could be creating and 
    starting a container as 
    in the case of Podman
end note

specific_wl_new -->> wl_facade_task --

... 

@enduml
