@startuml seq_restart_workload_on_update_with_create_failure
!include ../../../../resources/doc/plantuml/clean.skin

box "Ankaios Agent"
    participant "Workload" as workload
    participant "WorkloadCommandSender" as workload_command
    participant "<<task>>\nWorkloadControlLoop" as workload_control_loop

    participant "Specific Runtime Connector\n e.g., PodmanRuntime" as runtime
end box

workload_control_loop -> workload_command: wait for command

workload -> workload_command ++: send update command
workload_command -->> workload
workload_command -->> workload_control_loop --++: receive update
workload_control_loop -> runtime ++: delete
note right
    see delete digram for details on update
endnote
runtime -->> workload_control_loop--
workload_control_loop -> runtime ++: create workload
runtime -->> workload_control_loop--
opt create workload fails
    opt restart_counter < limit
        workload_control_loop ->> workload_control_loop ++: spawn restart
        workload_control_loop -> workload_command ++: send restart command
        workload_command -->> workload_control_loop--
    end
end
workload_control_loop -> workload_command --: wait for command
@enduml
