@startuml seq_logging_workflow
!include ../../../../resources/doc/plantuml/clean.skin

box "Collector Workload"
    participant "Workload" as collector_workload
end box

box "Agent A"
    participant "Agent" as agent_a
end box

box "Server"
    participant "Server" as server
end box

box "Agent B"
    participant "Agent" as agent_b
end box

participant "Logging workload" as logging_wl

activate collector_workload

group Requesting logs
    collector_workload -> agent_a ++: ank_base.LogsRequest
    agent_a ->> server --++: ank_base.LogsRequest

    server ->> agent_a ++: ank_base.LogsRequestAccepted
    agent_a -->> collector_workload --: ank_base.LogsRequestAccepted

    server ->> agent_b --++: ank_base.LogsRequest
    agent_b ->> agent_b--++: start sampling logs

end group

...

group Logs Stream
    logging_wl ->> agent_b: logs
    agent_b ->> server ++: ank_base.LogsResponse
    server ->> agent_a --++: ank_base.LogsResponse
    agent_a ->> collector_workload --: ank_base.LogsResponse
end group

...

group Stopping the logging campaign
    collector_workload -> agent_a ++: ank_base.LogsCancelRequest
    agent_a ->> server --++: ank_base.LogsCancelRequest

    server ->> agent_a ++: ank_base.LogsCancelAccepted
    agent_a -->> collector_workload --: ank_base.LogsCancelAccepted

    server ->> agent_b --: ank_base.LogsCancelRequest
    agent_b ->> agent_b: stop sampling logs
    deactivate agent_b

end group

@enduml
