@startuml seq_workload_files
!include ../../../../resources/doc/plantuml/clean.skin

box "Ankaios Agent"
    participant "WorkloadCommandChannel" as workload_command
    participant "WorkloadControlLoop" as workload_control_loop
    participant "WorkloadFilesCreator" as workload_files_creator
    participant "Specific Runtime Connector\n e.g., PodmanRuntime" as runtime
end box

== Initialization ==
[o->> workload_command++: send create
workload_control_loop -> workload_command++: wait for command
workload_command -->> workload_control_loop --++: receive create
deactivate workload_command
workload_control_loop -> workload_files_creator ++: create files
loop for each file in workload files
    workload_files_creator -> workload_files_creator++--: create host file path
    note left
        host workload file dir:
            /tmp/ankaios/<agent_name>_io/<workload_name>.<id>/files
        file.mountPoint: /some/file.conf
        host file path:
            /tmp/ankaios/<agent_name>_io/<workload_name>.<id>/files/some/file.conf
    end note
    workload_files_creator -> workload_files_creator++--: create host directory\nstructure
    workload_files_creator -> workload_files_creator++--: write workload file\nto host file path
    alt creation failed\nat some step
        workload_files_creator -> workload_files_creator++--: delete workload files\nsubfolder
        workload_files_creator -->> workload_control_loop: WorkloadFileCreationError
    else creation successful
        workload_files_creator -->> workload_control_loop--: host file path to\nmount point mappings
    end
end
workload_control_loop -> runtime ++: create(host file path to mount point mappings, ...)
runtime -> runtime++--: mount workload files
runtime -->> workload_control_loop--
opt create workload fails
    workload_control_loop -> workload_control_loop++--: delete workload files\nsubfolder
end
workload_control_loop -> workload_command --++: wait for command
...
@enduml
