@startuml seq_workload_delete
!include ../../../../resources/doc/plantuml/clean.skin

participant "<<RuntimeAdapter>>" as runtime_adapter
participant "Workload Facade" as wl_facade
participant "Workload Facade Task" as wl_facade_task
participant "specific Workload\n e.g. PodmanWorkload" as specific_wl


activate runtime_adapter


runtime_adapter -> wl_facade ++: stop 
note right
    This call consumes the
    Facade instance and
    thus makes it unusable
end note

wl_facade ->> wl_facade_task : send a "Stop" command over \n the communication channel
note right
    For more details about the
    channel see the start sequence
end note
activate wl_facade_task

wl_facade -->> runtime_adapter --:
destroy wl_facade

wl_facade_task -> specific_wl ++: stop specific Workload

specific_wl -> specific_wl ++--: do runtime specific \n stop Workload actions
note over specific_wl
The stop Workload actions
could be stopping and 
deleting a container as 
in the case of Podman
end note

specific_wl -->> wl_facade_task --

destroy wl_facade_task

... 

@enduml
