@startuml seq_workload_start
!include ../../../../resources/doc/plantuml/clean.skin

participant "<<RuntimeAdapter>>" as runtime_adapter
participant "Workload Facade" as wl_facade
participant "Workload Facade Task" as wl_facade_task
participant "specific Workload\n e.g. PodmanWorkload" as specific_wl


activate runtime_adapter

create wl_facade
runtime_adapter -> wl_facade ++: start a new Workload (specific Workload)

wl_facade -> wl_facade ++--: create a communication channel with tx rx
note right
    This creates an async communication
    that will be used to send commands to
    the freely running task
end note

wl_facade -> wl_facade ++--: store channel tx, i.e., sender

wl_facade ->> wl_facade_task **: spawn a new task (specific Workload, rx )
activate wl_facade_task

wl_facade -->> runtime_adapter --: Workload Facade object

wl_facade_task -> specific_wl ++: start specific Workload

specific_wl -> specific_wl ++--: do runtime specific \n start Workload actions
note over specific_wl
    The start Workload actions
    could be creating and 
    starting a container as 
    in the case of Podman
end note

specific_wl -->> wl_facade_task --

wl_facade_task -> wl_facade_task ++--: wait for further commands

... 

@enduml
