@startuml seq_update_workload_subsequent_deleted
!include ../../../../resources/doc/plantuml/clean.skin

box "Ankaios Agent"
    participant "AgentManager" as manager
    participant "RuntimeManager" as runtime_manager
    participant "Workload" as workload
end box

activate manager

...

manager -> runtime_manager ++: handle update workload

alt first update workload call for the current agent execution
... see dedicated digram for first call ...
else subsequent update workload call
    loop for each deleted Worload
        opt if the workload is also in the added workloads list
            runtime_manager -> runtime_manager ++--: remove workload from \n added workloads list
            runtime_manager -> runtime_manager ++: update workload
            runtime_manager -> runtime_manager ++--: find workload in running workloads
            alt workload object found
                runtime_manager -> workload ++: update (new config)
                workload ->> workload ++--: decopule the specific actions
                workload -->> runtime_manager --:
                deactivate runtime_manager
            else no workload object found -> nothing to update
                runtime_manager -> runtime_manager++--:add workload
                note right
                see add workload digram for details
                endnote
            end
        else
            runtime_manager -> runtime_manager ++--: remove workload from runtime workloads list
            runtime_manager -> workload ++: delete
            workload ->> workload ++--: decopule the specific action
            workload -->> runtime_manager --:
            destroy workload
        end
    end

    ... handle added Workloads ...

end

@enduml
