@startuml seq_logging_workflow
!include ../../../../resources/doc/plantuml/clean.skin

box "Collector Workload"
    participant "Workload" as collector_workload
end box

box "Agent A"
    participant "Agent" as agent_a
end box

box "Server"
    participant "Server" as server
end box

box "Agent B"
    participant "Agent" as agent_b
end box

box "Logger workload"
    participant "Logging process" as logger
end box

group Requesting logs
    collector_workload -> agent_a: ank_base.LogsRequest
    agent_a -> server: ank_base.LogsRequest
    server -> agent_b: ank_base.LogsRequest
    agent_b -> logger: *Start process*
    activate logger
    server -> agent_a: ank_base.LogsRequestAccepted
    agent_a -> collector_workload: ank_base.LogsRequestAccepted
end group

...

group Logs Stream
    logger -> agent_b: *Logs*
    agent_b -> server: ank_base.LogsResponse
    server -> agent_a: ank_base.LogsResponse
    agent_a -> collector_workload: ank_base.LogsResponse
end group

...

group Stopping the logging campaign
    collector_workload -> agent_a: ank_base.LogsCancelRequest
    agent_a -> server: ank_base.LogsCancelRequest
    server -> agent_b: ank_base.LogsCancelRequest
    agent_b -> logger: *Stop process*
    deactivate logger
    server -> agent_a: ank_base.LogsCancelAccepted
    agent_a -> collector_workload: ank_base.LogsCancelAccepted
end group

@enduml
