version = 'v1'

# Admission hooks are currently a beta feature. The configuration interface
# and the communication protocol between the server and hooks are unstable
# and can change at any time.
[[admission_hooks]]
name = 'example_hook'
prio = 10
