@startuml seq_update_state
!include ../../../../resources/doc/plantuml/clean.skin

box "Ankaios Server"
participant "<<thread>>\nAnkaiosServer" as server
participant "ServerState" as server_state
participant "<<thread>>\nGRPCCommunicationsServer" as grpc_server
participant "<<thread>>\ntonic gRPC server" as tonic_server
end box


box "Ankaios Agents"
participant "Agent 1" as agent1
participant "Agent 2" as agent2
end box

activate agent1
...
agent1 ->> tonic_server--++: UpdateState
tonic_server ->> server--++: UpdateState
server -> server_state++: update state
server_state -> server_state++--: create ExecutionRequest\nfrom comparison of new\nand old CurrentState
alt State valid
server_state -->> server--: ExecutionRequest
server ->> grpc_server++: send ExecutionRequests
grpc_server -->> server
deactivate server
opt ExuectionsRequests for Agent 1
grpc_server ->> agent1++:send ExecutionRequests
agent1 -> agent1++--: execute ExecutionRequests
deactivate agent1
end
opt ExuectionsRequests for Agent 2
grpc_server ->> agent2++:send ExecutionRequests
agent2 -> agent2++--: execute ExecutionRequests
deactivate agent2
end
deactivate grpc_server
else
server_state -->> server: UpdateStateError
end
server -> server++: listen for incoming requests


@enduml
