@startuml seq_set_wl_state_unknown_update
!include ../../../../resources/doc/plantuml/clean.skin

box "Ankaios Server"
participant "<<thread>>\nAnkaiosServer" as server
participant "<<thread>>\nGRPCCommunicationsServer" as grpc_server
participant "<<thread>>\ntonic gRPC server" as tonic_server
end box

box "Ankaios Agents"
participant "Agent1" as agent1
participant "Agent2" as agent2
end box

activate agent1
...Two agents are connected to Ankiaos Server...
agent1 ->> tonic_server --++: AgentGone
tonic_server ->> server --++: AgentGone
server -> server ++--: set workload states to ExecUnknown\n in WorkloadStateDB\n(Agent1)
note left server
        ""workloadStates:""
        ""- workload: Workload 1""
        ""  agent: Agent 1""
        ""  executionState: ExecUnknown""
end note

server ->> grpc_server --++: UpdateWorkloadState
grpc_server ->> agent2 --++: UpdateWorkloadState
note right agent2
        ""workloadStates:""
        ""- workload: Workload 1""
        ""  agent: Agent 1""
        ""  executionState: ExecUnknown""
end note

@enduml
