@startuml seq_update_state
!include ../../../../resources/doc/plantuml/clean.skin

box "Ankaios Server"
participant "<<thread>>\nAnkaiosServer" as server
participant "ServerState" as server_state
participant "<<thread>>\nGRPCCommunicationsServer" as grpc_server
participant "<<thread>>\ntonic gRPC server" as tonic_server
end box


box "Ankaios Agents"
participant "Agent 1" as agent1
participant "Agent 2" as agent2
end box

activate agent1
...
agent1 ->> tonic_server--++: UpdateStateRequest
tonic_server ->> server--++: UpdateStateRequest
server -> server_state++: update state
server_state -> server_state ++--: Generate new State based on\nupdate mask and\nnew and old DesiredState
server_state -> server_state ++--: Render the\ntemplated DesiredState
server_state -> server_state ++--: Validate the new State
server_state -> server_state ++--: Update DeleteGraph with\nDeleteConditions\nof new workloads
alt State valid
server_state -->> server--: Added and deleted workloads
server -> server++--: Create FromServer message from\nadded and deleted workloads
server ->> grpc_server++: send FromServer message
grpc_server -->> server
deactivate server
opt ExuectionsRequests for Agent 1
grpc_server ->> agent1++:send FromServer message
agent1 -> agent1++--: apply FromServer message
deactivate agent1
end
opt ExuectionsRequests for Agent 2
grpc_server ->> agent2++:send FromServer message
agent2 -> agent2++--: apply FromServer message
deactivate agent2
end
deactivate grpc_server
else
server_state -->> server ++: UpdateStateError
end
server -> server++: listen for incoming requests


@enduml
