@startuml seq_startup
!include ../../../../resources/doc/plantuml/clean.skin

box "Ankaios Server"
participant Main as main
participant "<<thread>>\nAnkaiosServer" as server

participant "<<thread>>\nGRPCCommunicationsServer" as grpc_server
participant "<<thread>>\ntonic gRPC server" as tonic_server
end box

box "Ankaios Agent"
    participant "Ankaios Agent" as agent
end box

agent <- ++: start

-> main ++
main -> main ++--: load startup config
note right: Empty state is loaded,\nif the startup config is empty.
main -> main ++--: create communication channels
main ->> grpc_server **: start
activate grpc_server
note over grpc_server
    start listening for
    FromServer messages
end note
main ->> server **: start with startup config
activate server
server -> server++--: validate startup config
alt startup config valid

loop per agent
    agent ->> grpc_server ++: agent hello (name)

    grpc_server ->> tonic_server **: spawn gRPC server thread
    deactivate grpc_server
    activate tonic_server
    tonic_server ->> server++: agent hello (name)
    note over tonic_server
        start listening for
        ToServer messages
    end note

    server -> server ++--: calculate commands to \n the specific agent

    server ->> grpc_server --++: send commands
    grpc_server ->> agent --++: forward commands
    note left
        the commands include
        new workloads and
        workload execution states
    end note
    ... Agent starts workloads according to commands ...
end

else
server -->> main--: startup config error
deactivate server
deactivate tonic_server

main -> main++--: Graceful shutdown
destroy grpc_server
destroy server
destroy main

end
@enduml
