@startuml seq_get_state
!include ../../../../resources/doc/plantuml/clean.skin

box "Ankaios Ank"
    actor "user" as user
    participant Main as main
    participant "CliCommands" as cli_commands
    participant "<<task>>\nListen to Ankaios\nServer" as listen_to_server
    participant "<<task>>\nListen to Agent \nManager" as listen_to_manager
end box

box "Ankaios Server"
    participant "Ankaios Server" as server
end box

-> main ++ : get state

== startup ==

... initialization ...

== command ==

main -> cli_commands ++ : get state
cli_commands ->> listen_to_manager ++: request complete state
listen_to_manager ->> server --++ : request complete state

cli_commands -> cli_commands ++: wait for the response
listen_to_server <<- server --++: complete state
listen_to_server ->> cli_commands --: complete state
cli_commands -> cli_commands ++: format output text
main <- cli_commands -- : output text
deactivate cli_commands
deactivate cli_commands
destroy cli_commands
destroy listen_to_manager
destroy listen_to_server

main -> main ++: print text
user <- main -- : exit
deactivate main
destroy main

@enduml
