@startuml seq_set_state
!include ../../../../resources/doc/plantuml/clean.skin

box "Ankaios Ank"
    actor "user" as user
    participant Main as main
    participant "CliCommands" as cli_commands
    participant "<<task>>\nListen to Ankaios\nServer" as listen_to_server
    participant "<<task>>\nListen to Agent \nManager" as listen_to_manager
end box

box "Ankaios Server"
    participant "Ankaios Server" as server
end box

-> main ++ : set state

== startup ==

... initialization ...

== command ==

main -> cli_commands ++ : set state
cli_commands ->> listen_to_manager ++: request update state
listen_to_manager ->> server --++ : request update state

cli_commands -> cli_commands ++: wait for the response

listen_to_server <<- server --++: response
listen_to_server ->> cli_commands --++: response
main <<-- cli_commands --
deactivate cli_commands

destroy cli_commands
destroy listen_to_manager
destroy listen_to_server

user <- main -- : exit
destroy main

@enduml
