#!/bin/bash

# Cleanup Ankaios ....
echo "Cleaning up Ankaios..."
pkill ank-agent
pkill ank-server
echo "OK."

# Cleanup podman
echo "Cleaning up podman..."
podman stop -a >/dev/null 2>&1
podman rm -a >/dev/null 2>&1
echo "OK."

# Cleanup certs
rm -rf .certs

# Cleanup tls env
echo "Cleaning up tls env..."
unset ANK_CA_PEM
unset ANK_CRT_PEM
unset ANK_KEY_PEM
