name: 'PR Tasks Completed Check'
on: 
  pull_request_target:
    types: [opened, edited]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
