name: GitHub Task List Checker
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  task-list-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check for incomplete task list items
        uses: Shopify/task-list-checker@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
