name: 'PR Tasks Completed Check'
on: 
  pull_request_target:
    types: [opened, edited, reopened, synchronized]
  
jobs:
  task-check:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
